image: node:latest

stages:
  - build

before_script:
  - npm install
  - npm rebuild node-sass

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    
build:
  stage: build
  script:
    - npm run build