image: node:latest

stages:
  - setup
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    
setup:
  stage: setup
  script:
     - rm ./package-lock.json
     - npm update
     - npm rebuild node-sass
     - npm view react-router-dom
     - npm install

build:
  stage: build
  script:
    - npm run build